server:
  port: 8520

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/website_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.0.101:3306/website_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: trsadmin
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#  application:
#    name: xxx
#  http:
#    encoding:
#      charset: UTF-8
#      force: true
#      enabled: true
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    cache: false
#    servlet:
#      content-type: text/html