#fileconfig:
#
##  file-path: /home/
#  file-path: D:\\workSpace\\Github Local Path\\GitHub\\Graduation-Project\\web_vue\\webpic\\picture\\
#
#  file-name: picture
spring:
  servlet:
    multipart:
      # 启用
      enabled: true
      # 上传文件单个限制
      max-file-size: 5MB
      # 总限制
      max-request-size: 6MB